version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'discord-management-bot2'
    working_dir: '/workspace/discord-management-bot2'
    tty: true
    env_file:
      - .env
    volumes:
      - .:/workspace/discord-management-bot2
